name: Main Workflow
on:
  push:
    branches:
      - main
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  call-workflow:
    uses: lpmag1/blazor-mssql-aws/.github/workflows/build.yml@main
