name: Main Workflow
on:
  push:
    branches:
      - main
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  build:
    uses: lpmag1/blazor-sqlite-aws/.github/workflows/build.yml@main
  deploy:
    needs: build
    uses: lpmag1/blazor-sqlite-aws/.github/workflows/deploy.yml@main
